#!/bin/bash -l
## Shell with login is required to manage .npmrcs located in user home

source ./__npmrc_help.sh

version=0.1.0
editor=${EDITOR:-vim}
npmrc_dir=${NPMRC_DIR:-"~"}
npmrc_filename=.npmrc

# list available npmrc profiles
function listProfiles() {
    local home_path=`echo ~`
    ls $home_path/$npmrc_filename.* | sed 's,'"$home_path/$npmrc_filename."',,'
}

# check if profile is defined
# @param $1 profile
function checkProfile() {
    if [ -z "$1" ] ; then
        echo "Error > Missing profile name!"
        echo "Available profiles:" `listProfiles`
        exit 1
    fi
}

# check if profile is in existing profiles
# @param $1 profile name
function checkExistingProfile() {
    listProfiles
}

# switch to other profile
# @param $1 profile name
function use() {
    checkProfile $1

    bash -lc "cp ~/$npmrc_filename.$1 ~/$npmrc_filename"

    echo "Now using profile: $1"
    echo Registry: $(npm get registry)
}

# edit or create a profile
# @param $1 profile name
function edit() {
    if [ -z "$1" ] ; then
        __edit_help
    fi

    checkProfile $1

    echo "Editing profile: $1"
    bash -lc "$editor ~/$npmrc_filename.$1"
}

# delete a profile
# @param $1 profile name
# @param $2? -y flag skip confirmation
function delete() {
    if [ -z "$1" ] ; then
        __delete_help
    fi

    checkProfile $1

    echo "Removing profile: $1"

    if [ "$2" == "-y" ] ; then
        REPLY="y"
    else
        read -p "Are you sure? (y/N) " -n 1 -r
    fi

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
        echo
        bash -lc "rm -f ~/$npmrc_filename.$1"
    else
        echo
    fi
}

# list all profiles
# @param $1? -l flag list as multiline
function list() {
    local profiles=`listProfiles`

    if [ "$1" == "-l" ] ; then
        echo "$profiles"
    else
        echo $profiles
    fi
}

function version() {
    echo $version
}

function main() {
    case "$1" in
        use) use $2;;
        edit) edit $2;;
        ed) edit $2;;
        delete) delete $2 $3;;
        del) delete $2 $3;;
        
        list) list $2;;
        ls) list $2;;
        -v) version;;
        --version) version;;
        version) version;;
        help) __help $0;;
        --help) __help $0;;
        -h) __help $0;;
        *) __help $0;;
    esac
}

main "$@"
